import { Lato } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/darkMode/Provider";
import { Navbar } from "@/components";
import App from "./App";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer";
import WhatsAppButton from "@/components/WhatsAppButton";
const poppins = Lato({ subsets: ["latin"], weight: ['300', '400', '700', '900'] });

export const metadata = {
  title: "e-commernce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">

      <body className={poppins.className}>
        <div className="relative">
          <Providers>
            <App>
              <Navbar />
              {children}
              <WhatsAppButton />
              <Footer />
            </App>
          </Providers>
        </div>

        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
