import { Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/darkMode/Provider";
import { Navbar } from "@/components";
import App from "./app";
import { Toaster } from "react-hot-toast";

const poppins = Poppins({ subsets: ["latin"], weight: ['300', '500', '600', '700', '400'] });

export const metadata = {
  title: "e-commernce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Providers>
          <App>
            <Navbar />
            {children}
          </App>
        </Providers>

        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
